apiVersion: v1
kind: ConfigMap
metadata:
  name: router-configmap
data:
  spring_jpa_hibernate_ddl-auto: "update"
  spring.datasource.url: "jdbc:mysql://mariadb-service:3306/flw4?useSSL=false"
  spring.datasource.username: "flw4"

     

---
apiVersion: v1
kind: Secret
metadata:
  name: router-secrets
type: Opaque
data:
  spring.datasource.password: YzJPUnE4MVZHTTdiY1VTZjQ1Nkw=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-deployment
  labels:
    app: routerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routerservice
  template:
    metadata:
      labels:
        app: routerservice
    spec:
      containers:
      - name: router
        image: docker.flexwhere.com/flw_router:FR30092022
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: router-configmap
          - secretRef:
              name: router-secrets
      imagePullSecrets:
      - name: fwregistry-secret
      nodeSelector:
        nodeLabelname: fwtestnode1
---
apiVersion: v1
kind: Service
metadata:
  name: router-service
spec:
  selector:
    app: routerservice
  ports:
    - name: routerport
      protocol: TCP
      port: 8098
      targetPort: 8080
