apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: flexwherefrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flexwherefrontend
  template:
    metadata:
      labels:
        app: flexwherefrontend
    spec:
      containers:
      - name: flexwherefrontend
        image: docker.flexwhere.com/flexwhere_frontend:production
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: fwregistry-secret
      nodeSelector:
        nodeLabelname: fwtestnode1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: flexwherefrontend
spec:
  selector:
    app: flexwherefrontend
  type: NodePort
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32767
